ingress:
  enabled: true
  className: nginx
  host: ai-mesh.local

storageClass: local-path

services:
  - name: gateway
    image: ghcr.io/kwal0203/ai-mesh-gateway:dev
    port: 8000
    path: /
  - name: embedding
    image: ghcr.io/kwal0203/ai-mesh-embedding:dev
    port: 8001
    path: /embedding
  - name: classifier
    image: ghcr.io/kwal0203/ai-mesh-classifier:dev
    port: 8002
    path: /classifier
  - name: eval
    image: ghcr.io/kwal0203/ai-mesh-eval:dev
    port: 8003
    path: /eval
